apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-13T19:20:20Z"
  generation: 1
  labels:
    app: javascript-basic
  name: javascript-basic
  namespace: default
  resourceVersion: "33806"
  selfLink: /apis/apps/v1/namespaces/default/deployments/javascript-basic
  uid: 7362b365-6bd2-4a7b-8b12-2d31e0d4f957
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: javascript-basic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javascript-basic
    spec:
      containers:
      - image: caprilespe/javascript-basic:v1
        imagePullPolicy: IfNotPresent
        name: javascript-basic
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-08-13T19:20:20Z"
    lastUpdateTime: "2021-08-13T19:21:00Z"
    message: ReplicaSet "javascript-basic-86ccc4cb8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-08-13T19:22:48Z"
    lastUpdateTime: "2021-08-13T19:22:48Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
